module.exports = {
  extensionId: 'metadata-editor',
  priConExtensionId: 'precon-editor',
  shopByLookExtensionID: 'shopbylook-editor',
  techDataExtensionID: 'techdata-editor',
  BASE_DEV : "https://productdata-int1.api.bmw//pdh/categoryhub/v1.0/all/",
  BASE_PROD : "https://productdata.api.bmw//pdh/categoryhub/v1.0/all/",
  MODEL_BASE_URL : "https://productdata.api.bmw/pdh/technicaldata/v2.0/model/",
  LATEST : "/latest",
  PRECON_PROD_URL : "https://productdata.api.bmw/pdh/precons/v1.0",
  SERIES : "/series/",
  RANGE : "/ranges/",
  VEHICLES : "/vehicles/",
  VEHICLE : "/vehicle/",
}